spring:
  config:
    import: "optional:configserver:http://j9c211.p.ssafy.io:62110" #config server uri
  cloud:
    config:
      name: member
      profile: local

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  servlet:
    multipart:
      maxFileSize: 10MB # 파일 하나의 최대 크기
      maxRequestSize: 30MB  # 한 번에 최대 업로드 가능 용량
encrypt:
  key: ${ssh-encrypt-key}

file:
  dir: C:/dev/

logging:
  level:
    com.ts.taesan.domain.transaction.req: DEBUG
    com.ts.taesan.domain.analyst.req: DEBUG
