spring:
  config:
    import: "optional:configserver:http://j9c211.p.ssafy.io:62110" #config server uri
  cloud:
    config:
      name: member
      profile: local

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
encrypt:
  key: ${ssh-encrypt-key}
